### ISSUE TITLE
Running the program

### ISSUE THREAD

**Issue by RogerMultiplo** [Chillee/CV-Maze-Solver#1]
Hi there!
I'm quite a newbie in the python world.

I've tried running your program but it didn't work. When I tried to run the builder I got the following error:
building 'connections' extension
Traceback (most recent call last):
  File "./setup.py", line 18, in <module>
    ext_modules=cythonize(extensions, annotate=True)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']

And as it can't compile the connections extension, when I call profile file
"python profile.py circular_maze1.png" I get the error "ImportError: No module named connections".

Could you help me get it running?

Thanks!

**Comment by olivia-fl** [comment]
I'm not exactly sure what's going on in that error, but I have some guesses. The relevant code in distutils is [here](https://github.com/python/cpython/blob/2cf1ddaff4c869780d9e796b21ef3e506f8ad321/Lib/distutils/msvc9compiler.py#L253). There's also [this](https://bugs.python.org/issue7511) issue on the python bug tracker which looks like what's happening to you. There are a whole bunch of proposed solutions in that thread, so you can go try theme. Somebody near the bottom says that there's a separate version of msvc for python that you have to install.

If it's an option, I would highly recommend just installing gcc or clang. They are both *way* less fiddly than msvc. If you have a linux or mac computer, that would also probably work without much effort.

I'm closing this issue since it's a problem with distutils and msvc rather than a problem with this program, but I can definitely help troubleshoot further.
